# Common Data Types in NumPy:
- int32, int64: Integer types with different bit sizes.
- float32, float64: Floating-point types with different precision.
- bool: Boolean data type.
- complex64, complex128: Complex number types.
- object: For storing objects (e.g., Python objects, strings).

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

int64


In [3]:
arr.astype('float64')

array([1., 2., 3., 4., 5.])

In [4]:
arr

array([1, 2, 3, 4, 5])

# Memory usage

In [5]:
arr_int64 = np.array([1, 2, 3], dtype='int64')
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


# String Data Type in NumPy
- Although NumPy arrays typically store numerical data, you can also store strings by using the dtype='str' or dtype='U' (Unicode string) format. However, working with strings in NumPy is less efficient than using lists or Python's built-in string types.

In [6]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


# Complex Numbers
- NumPy also supports complex numbers, which consist of a real and imaginary part. You can store complex numbers using complex64 or complex128 data types

In [7]:
cmplx = np.array([3 + 7j, 5 - 6j, 6 + 9j], dtype='complex128')

In [8]:
cmplx

array([3.+7.j, 5.-6.j, 6.+9.j])

# Object Data Type
- If you need to store mixed or complex data types (e.g., Python objects), you can use dtype='object'. However, this type sacrifices performance, so it should only be used when absolutely necessary.

In [9]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
