In [1]:
import numpy as np

In [2]:
arr = np.array([3, 5, 1, 37, 69])

In [3]:
np.mean(arr) # Mean/average of an array

np.float64(23.0)

In [5]:
np.min(arr)

np.int64(1)

In [6]:
np.max(arr)

np.int64(69)

In [7]:
np.sum(arr)

np.int64(115)

In [9]:
np.prod(arr)

np.int64(38295)

In [10]:
np.std(arr) # std -- Standard deviation

np.float64(26.5329983228432)

In [11]:
np.var(arr)  # var -- Variance

np.float64(704.0)

In [12]:
np.median(arr)

np.float64(5.0)

In [14]:
np.percentile(arr, 3)

np.float64(1.24)

In [15]:
np.argmin(arr) # returns the index of minimum value

np.int64(2)

In [16]:
arr2 = np.array([1, 2, 3, 4, 5])

In [17]:
np.corrcoef(arr, arr2) #  Compute the correlation coefficient matrix of two arrays.

array([[1.        , 0.87412294],
       [0.87412294, 1.        ]])

In [18]:
arr3 = np.array([1, 1, 2, 3, 2, 4, 4, 4, 3, 7, 6, 6, 7])

In [19]:
np.unique(arr3)

array([1, 2, 3, 4, 6, 7])

In [20]:
np.cumsum(arr) # Cumulative sum of array

array([  3,   8,   9,  46, 115])

In [21]:
np.diff(arr) # diff (right element - left element)

array([ 2, -4, 36, 32])

In [22]:
np.linspace(0, 15, 4) # 4 evenly spaced numbers between 0 to 15

array([ 0.,  5., 10., 15.])

In [24]:
np.log(arr) # natural log of an array

array([1.09861229, 1.60943791, 0.        , 3.61091791, 4.2341065 ])

In [25]:
np.exp(arr2) # exponential

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])