In [3]:
import numpy as np

In [2]:
arr = np.array([1, 2, 4])

In [3]:
arr

array([1, 2, 4])

In [4]:
# 1D array
arr1 = np.array([1,3,5])
arr1

array([1, 3, 5])

In [5]:
# 2D array
arr2 = np.array([[1,5,7],[3,8,2]])
arr2

array([[1, 5, 7],
       [3, 8, 2]])

- Unlike lists, all elements must have the same data types.

In [6]:
# array of ZEROS
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# array of ONES
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# array of any other Number
np.full((3,3),69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [9]:
# Identity Matrix array
np.eye(3) # Identity Matrix of 3X3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Arange array
np.arange(1, 30, 4)  # [1, 1+ 4, 1 + 4 + 4, ..]

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [11]:
# np.linspace -- gives evenly spaced array
np.linspace(1, 100, 4) # Gives 4 evenly spaced array between 1 to 100.

array([  1.,  34.,  67., 100.])

In [12]:
arr3 = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr3.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr3.size)     # 6 → total elements
print("Dimensions:", arr3.ndim) # 2 → 2D array
print("Data type:", arr3.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [14]:
# Changing Data types
arr4 = np.array([[10, 20, 30], [40, 50, 60]], dtype = 'float32')
arr4

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [15]:
arr5 = arr4.astype('float64')
arr5

array([[10., 20., 30.],
       [40., 50., 60.]])

In [16]:
arr4.dtype # 'float32'

dtype('float32')

In [17]:
arr5.dtype # 'float64'

dtype('float64')

In [21]:
arr5 = np.array([3, 7, 6, 9], dtype = np.float32)
arr5

array([3., 7., 6., 9.], dtype=float32)

In [23]:
arr6 = arr5.astype(np.int32)
arr6

array([3, 7, 6, 9], dtype=int32)

# Reshaping
- Changes order of matrix

In [20]:
arr7 = np.array([[3, 5, 9],[84, 69, 37],[123, 54, 4],[314, 167, 27]])  # 4X3 Matrix

In [21]:
arr7

array([[  3,   5,   9],
       [ 84,  69,  37],
       [123,  54,   4],
       [314, 167,  27]])

In [22]:
arr7.reshape((3,4)) # # 3X4 Matrix

array([[  3,   5,   9,  84],
       [ 69,  37, 123,  54],
       [  4, 314, 167,  27]])

In [28]:
arr7.reshape((6,2)) # 6X2 Matrix

array([[  3,   5],
       [  9,  84],
       [ 69,  37],
       [123,  54],
       [  4, 314],
       [167,  27]])

# Flatten
- changes dimension

In [29]:
arr7.flatten()

array([  3,   5,   9,  84,  69,  37, 123,  54,   4, 314, 167,  27])