In [14]:
import numpy as np

In [15]:
arr = np.array([[3, 5, 9],[84, 69, 37],[123, 54, 4],[314, 167, 27]])
arr

array([[  3,   5,   9],
       [ 84,  69,  37],
       [123,  54,   4],
       [314, 167,  27]])

In [16]:
flat = arr.flatten()
flat

array([  3,   5,   9,  84,  69,  37, 123,  54,   4, 314, 167,  27])

In [17]:
flat[4]

np.int64(69)

In [18]:
flat[3:7] # 3 to 6

array([ 84,  69,  37, 123])

In [19]:
flat[::4] # Every 4th Elements

array([ 3, 69,  4])

# Slicing returns a view, not a copy!
- changes in sliced array affects the original array.

In [20]:
flat

array([  3,   5,   9,  84,  69,  37, 123,  54,   4, 314, 167,  27])

In [21]:
sliced = flat[4:9]

In [22]:
sliced

array([ 69,  37, 123,  54,   4])

In [25]:
sliced[1] = 0 # Original array will be changed also.

In [26]:
flat

array([  3,   5,   9,  84,  69,   0, 123,  54,   4, 314, 167,  27])

# Creating Copy

In [29]:
copy = flat[5:9].copy()

In [30]:
copy

array([  0, 123,  54,   4])

In [31]:
copy[0] = 37
copy

array([ 37, 123,  54,   4])

# Fancy indexing and boolean masking

In [35]:
arr1 = np.array([2, 6, 8, 4, 9, 0])

In [36]:
arr1[[1, 3, 4]] # Returns elements at given indices.

array([6, 4, 9])

In [38]:
arr1[arr1>4] 

array([6, 8, 9])

In [43]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
even = num[num % 2 == 0]

In [45]:
even

array([2, 4, 6, 8])

In [46]:
_3d = num.reshape((3,3))

In [47]:
_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
flot = np.array([1.1, 2.3, 3.5, 4.12])

In [49]:
flot_to_int = flot.astype(np.int32)

In [50]:
flot_to_int

array([1, 2, 3, 4], dtype=int32)