# Multidimensional Indexing and Axis in Numpy

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],  #-- 0th row
                [4, 5, 6],   #-- 1st row
                [7, 8, 9]])  #-- 2nd row

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
arr.shape  # (no of rows, no of columns)

(3, 3)

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[2]

array([7, 8, 9])

- axis=0 : refers to all rows.
- axis=1 : refers to all columns.

In [5]:
np.sum( arr, axis=0)  # along each rows (down each column)

array([12, 15, 18])

In [6]:
np.sum(arr, axis=1)  # along each column (down each row)

array([ 6, 15, 24])

In [7]:
arr[1][2] # 1st row and 2nd column

np.int64(6)

In [8]:
arr[1, 2] # 1st row and 2nd column

np.int64(6)

In [9]:
arr[1:3, 0:2] # 1st row to 2nd row and 0th column to 1st column

array([[4, 5],
       [7, 8]])

- 3D Array and it's indexing

In [14]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],  # 0th depth
                  [[7, 8, 9], [10, 11, 12]]])  # 1st depth

In [15]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3)

(2, 2, 3)


In [17]:
arr3D[0, 1, 1]

np.int64(5)

In [20]:
arr3D[0:2, 0:2, 1:3]  # Depth: oth to 1st, Row: 0th to 1st, Column: 1st to 2nd

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [30]:
arr3x3 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],
                  [[10, 11, 12],[13, 14, 15],[16, 17, 18]],
                  [[19, 20, 21],[22, 23, 24],[25, 26, 27]]])

In [31]:
arr3x3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [36]:
arr3x3[1, :, :] = 0

In [37]:
arr3x3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])